//
// File generated by rootcint at Sun Jul  7 17:10:37 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME RawClusterBuilderTemplateSub_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "RawClusterBuilderTemplateSub_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void RawClusterBuilderTemplateSub_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void RawClusterBuilderTemplateSub_Dictionary();
   static void *new_RawClusterBuilderTemplateSub(void *p = 0);
   static void *newArray_RawClusterBuilderTemplateSub(Long_t size, void *p);
   static void delete_RawClusterBuilderTemplateSub(void *p);
   static void deleteArray_RawClusterBuilderTemplateSub(void *p);
   static void destruct_RawClusterBuilderTemplateSub(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::RawClusterBuilderTemplateSub*)
   {
      ::RawClusterBuilderTemplateSub *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::RawClusterBuilderTemplateSub),0);
      static ::ROOT::TGenericClassInfo 
         instance("RawClusterBuilderTemplateSub", "./RawClusterBuilderTemplateSub.h", 16,
                  typeid(::RawClusterBuilderTemplateSub), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &RawClusterBuilderTemplateSub_Dictionary, isa_proxy, 3,
                  sizeof(::RawClusterBuilderTemplateSub) );
      instance.SetNew(&new_RawClusterBuilderTemplateSub);
      instance.SetNewArray(&newArray_RawClusterBuilderTemplateSub);
      instance.SetDelete(&delete_RawClusterBuilderTemplateSub);
      instance.SetDeleteArray(&deleteArray_RawClusterBuilderTemplateSub);
      instance.SetDestructor(&destruct_RawClusterBuilderTemplateSub);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::RawClusterBuilderTemplateSub*)
   {
      return GenerateInitInstanceLocal((::RawClusterBuilderTemplateSub*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::RawClusterBuilderTemplateSub*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void RawClusterBuilderTemplateSub_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::RawClusterBuilderTemplateSub*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_RawClusterBuilderTemplateSub(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RawClusterBuilderTemplateSub : new ::RawClusterBuilderTemplateSub;
   }
   static void *newArray_RawClusterBuilderTemplateSub(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::RawClusterBuilderTemplateSub[nElements] : new ::RawClusterBuilderTemplateSub[nElements];
   }
   // Wrapper around operator delete
   static void delete_RawClusterBuilderTemplateSub(void *p) {
      delete ((::RawClusterBuilderTemplateSub*)p);
   }
   static void deleteArray_RawClusterBuilderTemplateSub(void *p) {
      delete [] ((::RawClusterBuilderTemplateSub*)p);
   }
   static void destruct_RawClusterBuilderTemplateSub(void *p) {
      typedef ::RawClusterBuilderTemplateSub current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::RawClusterBuilderTemplateSub

/********************************************************
* RawClusterBuilderTemplateSub_Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableRawClusterBuilderTemplateSub_Dict();

extern "C" void G__set_cpp_environmentRawClusterBuilderTemplateSub_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("RawClusterBuilderTemplateSub.h");
  G__cpp_reset_tagtableRawClusterBuilderTemplateSub_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevRawClusterBuilderTemplateSub_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* RawClusterBuilderTemplateSub */
static int G__RawClusterBuilderTemplateSub_Dict_192_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RawClusterBuilderTemplateSub* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new RawClusterBuilderTemplateSub(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) RawClusterBuilderTemplateSub(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new RawClusterBuilderTemplateSub[n];
       } else {
         p = new((void*) gvp) RawClusterBuilderTemplateSub[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new RawClusterBuilderTemplateSub;
       } else {
         p = new((void*) gvp) RawClusterBuilderTemplateSub;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RawClusterBuilderTemplateSub_Dict_192_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawClusterBuilderTemplateSub*) G__getstructoffset())->set_threshold_energy((const float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RawClusterBuilderTemplateSub_Dict_192_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((RawClusterBuilderTemplateSub*) G__getstructoffset())->setEnergyNorm((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RawClusterBuilderTemplateSub_Dict_192_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((RawClusterBuilderTemplateSub*) G__getstructoffset())->checkenergy((const int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((RawClusterBuilderTemplateSub*) G__getstructoffset())->checkenergy();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RawClusterBuilderTemplateSub_Dict_192_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   RawClusterBuilderTemplateSub* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new RawClusterBuilderTemplateSub(*(RawClusterBuilderTemplateSub*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RawClusterBuilderTemplateSub G__TRawClusterBuilderTemplateSub;
static int G__RawClusterBuilderTemplateSub_Dict_192_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (RawClusterBuilderTemplateSub*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((RawClusterBuilderTemplateSub*) (soff+(sizeof(RawClusterBuilderTemplateSub)*i)))->~G__TRawClusterBuilderTemplateSub();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (RawClusterBuilderTemplateSub*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((RawClusterBuilderTemplateSub*) (soff))->~G__TRawClusterBuilderTemplateSub();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__RawClusterBuilderTemplateSub_Dict_192_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   RawClusterBuilderTemplateSub* dest = (RawClusterBuilderTemplateSub*) G__getstructoffset();
   *dest = *(RawClusterBuilderTemplateSub*) libp->para[0].ref;
   const RawClusterBuilderTemplateSub& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* RawClusterBuilderTemplateSub */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncRawClusterBuilderTemplateSub_Dict {
 public:
  G__Sizep2memfuncRawClusterBuilderTemplateSub_Dict(): p(&G__Sizep2memfuncRawClusterBuilderTemplateSub_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncRawClusterBuilderTemplateSub_Dict::*p)();
};

size_t G__get_sizep2memfuncRawClusterBuilderTemplateSub_Dict()
{
  G__Sizep2memfuncRawClusterBuilderTemplateSub_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceRawClusterBuilderTemplateSub_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub))) {
     RawClusterBuilderTemplateSub *G__Lderived;
     G__Lderived=(RawClusterBuilderTemplateSub*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub),G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub),G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableRawClusterBuilderTemplateSub_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* RawClusterBuilderTemplateSub */
static void G__setup_memvarRawClusterBuilderTemplateSub(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub));
   { RawClusterBuilderTemplateSub *p; p=(RawClusterBuilderTemplateSub*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterContainer),-1,-1,4,"_clusters=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_BEmcRecCEMC),-1,-1,4,"bemc=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fEnergyNorm=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"_min_tower_e=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"chkenergyconservation=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_string),-1,-1,4,"ClusterNodeName=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarRawClusterBuilderTemplateSub_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncRawClusterBuilderTemplateSub(void) {
   /* RawClusterBuilderTemplateSub */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub));
   G__memfunc_setup("RawClusterBuilderTemplateSub",2873,G__RawClusterBuilderTemplateSub_Dict_192_0_1, 105, G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"RawClusterBuilderGraph\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_threshold_energy",2145,G__RawClusterBuilderTemplateSub_Dict_192_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 10 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEnergyNorm",1362,G__RawClusterBuilderTemplateSub_Dict_192_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - norm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("checkenergy",1160,G__RawClusterBuilderTemplateSub_Dict_192_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 '1' i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateNodes",1101,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CorrectPhi",1011,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 3, 1, 4, 0, 
"U 'RawCluster' - 0 - cluster U 'RawTowerContainer' - 0 - towers "
"U 'RawTowerGeomContainer' - 0 - towergemom", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cell2Abs",712,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 5, 1, 4, 0, 
"U 'RawTowerGeomContainer' - 0 - towergeom f - - 0 - phiC "
"f - - 0 - etaC f - - 1 - phi "
"f - - 1 - eta", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("RawClusterBuilderTemplateSub", 2873, G__RawClusterBuilderTemplateSub_Dict_192_0_11, (int) ('i'), 
G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub), -1, 0, 1, 1, 1, 0, "u 'RawClusterBuilderTemplateSub' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~RawClusterBuilderTemplateSub", 2999, G__RawClusterBuilderTemplateSub_Dict_192_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__RawClusterBuilderTemplateSub_Dict_192_0_13, (int) ('u'), G__get_linked_tagnum(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub), -1, 1, 1, 1, 1, 0, "u 'RawClusterBuilderTemplateSub' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncRawClusterBuilderTemplateSub_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalRawClusterBuilderTemplateSub_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcRawClusterBuilderTemplateSub_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawCluster = { "RawCluster" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawClusterContainer = { "RawClusterContainer" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawTowerContainer = { "RawTowerContainer" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawTowerGeomContainer = { "RawTowerGeomContainer" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_BEmcRecCEMC = { "BEmcRecCEMC" , 99 , -1 };
G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub = { "RawClusterBuilderTemplateSub" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableRawClusterBuilderTemplateSub_Dict() {
  G__RawClusterBuilderTemplateSub_DictLN_string.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_Fun4AllBase.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_PHCompositeNode.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_SubsysReco.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_RawCluster.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_RawClusterContainer.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_RawTowerContainer.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_RawTowerGeomContainer.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_BEmcRecCEMC.tagnum = -1 ;
  G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableRawClusterBuilderTemplateSub_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_string);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_RawCluster);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterContainer);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_RawTowerContainer);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_RawTowerGeomContainer);
   G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_BEmcRecCEMC);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub),sizeof(RawClusterBuilderTemplateSub),-1,197888,(char*)NULL,G__setup_memvarRawClusterBuilderTemplateSub,G__setup_memfuncRawClusterBuilderTemplateSub);
}
extern "C" void G__cpp_setupRawClusterBuilderTemplateSub_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupRawClusterBuilderTemplateSub_Dict()");
  G__set_cpp_environmentRawClusterBuilderTemplateSub_Dict();
  G__cpp_setup_tagtableRawClusterBuilderTemplateSub_Dict();

  G__cpp_setup_inheritanceRawClusterBuilderTemplateSub_Dict();

  G__cpp_setup_typetableRawClusterBuilderTemplateSub_Dict();

  G__cpp_setup_memvarRawClusterBuilderTemplateSub_Dict();

  G__cpp_setup_memfuncRawClusterBuilderTemplateSub_Dict();
  G__cpp_setup_globalRawClusterBuilderTemplateSub_Dict();
  G__cpp_setup_funcRawClusterBuilderTemplateSub_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRawClusterBuilderTemplateSub_Dict();
  return;
}
class G__cpp_setup_initRawClusterBuilderTemplateSub_Dict {
  public:
    G__cpp_setup_initRawClusterBuilderTemplateSub_Dict() { G__add_setup_func("RawClusterBuilderTemplateSub_Dict",(G__incsetup)(&G__cpp_setupRawClusterBuilderTemplateSub_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initRawClusterBuilderTemplateSub_Dict() { G__remove_setup_func("RawClusterBuilderTemplateSub_Dict"); }
};
G__cpp_setup_initRawClusterBuilderTemplateSub_Dict G__cpp_setup_initializerRawClusterBuilderTemplateSub_Dict;

