/********************************************************************
* RawClusterBuilderTemplateSub_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RawClusterBuilderTemplateSub_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_inheritanceRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_typetableRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_memvarRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_globalRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_memfuncRawClusterBuilderTemplateSub_Dict();
extern void G__cpp_setup_funcRawClusterBuilderTemplateSub_Dict();
extern void G__set_cpp_environmentRawClusterBuilderTemplateSub_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RawClusterBuilderTemplateSub.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_string;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_Fun4AllBase;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_PHCompositeNode;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_SubsysReco;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawCluster;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawClusterContainer;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawTowerContainer;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawTowerGeomContainer;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_BEmcRecCEMC;
extern G__linked_taginfo G__RawClusterBuilderTemplateSub_DictLN_RawClusterBuilderTemplateSub;

/* STUB derived class for protected member access */
