//
// File generated by rootcint at Sun Jul  7 18:36:38 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SubtractCEMC_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SubtractCEMC_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SubtractCEMC_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void SubtractCEMC_Dictionary();
   static void *new_SubtractCEMC(void *p = 0);
   static void *newArray_SubtractCEMC(Long_t size, void *p);
   static void delete_SubtractCEMC(void *p);
   static void deleteArray_SubtractCEMC(void *p);
   static void destruct_SubtractCEMC(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SubtractCEMC*)
   {
      ::SubtractCEMC *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::SubtractCEMC),0);
      static ::ROOT::TGenericClassInfo 
         instance("SubtractCEMC", "./SubtractCEMC.h", 24,
                  typeid(::SubtractCEMC), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &SubtractCEMC_Dictionary, isa_proxy, 1,
                  sizeof(::SubtractCEMC) );
      instance.SetNew(&new_SubtractCEMC);
      instance.SetNewArray(&newArray_SubtractCEMC);
      instance.SetDelete(&delete_SubtractCEMC);
      instance.SetDeleteArray(&deleteArray_SubtractCEMC);
      instance.SetDestructor(&destruct_SubtractCEMC);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SubtractCEMC*)
   {
      return GenerateInitInstanceLocal((::SubtractCEMC*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SubtractCEMC*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void SubtractCEMC_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::SubtractCEMC*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_SubtractCEMC(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SubtractCEMC : new ::SubtractCEMC;
   }
   static void *newArray_SubtractCEMC(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SubtractCEMC[nElements] : new ::SubtractCEMC[nElements];
   }
   // Wrapper around operator delete
   static void delete_SubtractCEMC(void *p) {
      delete ((::SubtractCEMC*)p);
   }
   static void deleteArray_SubtractCEMC(void *p) {
      delete [] ((::SubtractCEMC*)p);
   }
   static void destruct_SubtractCEMC(void *p) {
      typedef ::SubtractCEMC current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::SubtractCEMC

/********************************************************
* SubtractCEMC_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSubtractCEMC_Dict();

extern "C" void G__set_cpp_environmentSubtractCEMC_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SubtractCEMC.h");
  G__cpp_reset_tagtableSubtractCEMC_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSubtractCEMC_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SubtractCEMC */
static int G__SubtractCEMC_Dict_187_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SubtractCEMC* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SubtractCEMC(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) SubtractCEMC(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SubtractCEMC[n];
       } else {
         p = new((void*) gvp) SubtractCEMC[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SubtractCEMC;
       } else {
         p = new((void*) gvp) SubtractCEMC;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SubtractCEMC_Dict_187_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SubtractCEMC*) G__getstructoffset())->SetFlowModulation((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SubtractCEMC_Dict_187_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SubtractCEMC* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SubtractCEMC(*(SubtractCEMC*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SubtractCEMC G__TSubtractCEMC;
static int G__SubtractCEMC_Dict_187_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SubtractCEMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SubtractCEMC*) (soff+(sizeof(SubtractCEMC)*i)))->~G__TSubtractCEMC();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SubtractCEMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SubtractCEMC*) (soff))->~G__TSubtractCEMC();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SubtractCEMC_Dict_187_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SubtractCEMC* dest = (SubtractCEMC*) G__getstructoffset();
   *dest = *(SubtractCEMC*) libp->para[0].ref;
   const SubtractCEMC& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SubtractCEMC */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSubtractCEMC_Dict {
 public:
  G__Sizep2memfuncSubtractCEMC_Dict(): p(&G__Sizep2memfuncSubtractCEMC_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSubtractCEMC_Dict::*p)();
};

size_t G__get_sizep2memfuncSubtractCEMC_Dict()
{
  G__Sizep2memfuncSubtractCEMC_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSubtractCEMC_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC))) {
     SubtractCEMC *G__Lderived;
     G__Lderived=(SubtractCEMC*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC),G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC),G__get_linked_tagnum(&G__SubtractCEMC_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSubtractCEMC_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SubtractCEMC */
static void G__setup_memvarSubtractCEMC(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC));
   { SubtractCEMC *p; p=(SubtractCEMC*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_use_flow_modulation=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSubtractCEMC_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSubtractCEMC(void) {
   /* SubtractCEMC */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC));
   G__memfunc_setup("SubtractCEMC",1120,G__SubtractCEMC_Dict_187_0_1, 105, G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"SubtractCEMC\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetFlowModulation",1760,G__SubtractCEMC_Dict_187_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - use_flow_modulation", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateNode",986,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("SubtractCEMC", 1120, G__SubtractCEMC_Dict_187_0_6, (int) ('i'), G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC), -1, 0, 1, 1, 1, 0, "u 'SubtractCEMC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SubtractCEMC", 1246, G__SubtractCEMC_Dict_187_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SubtractCEMC_Dict_187_0_8, (int) ('u'), G__get_linked_tagnum(&G__SubtractCEMC_DictLN_SubtractCEMC), -1, 1, 1, 1, 1, 0, "u 'SubtractCEMC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSubtractCEMC_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSubtractCEMC_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSubtractCEMC_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SubtractCEMC_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__SubtractCEMC_DictLN_SubtractCEMC = { "SubtractCEMC" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSubtractCEMC_Dict() {
  G__SubtractCEMC_DictLN_string.tagnum = -1 ;
  G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SubtractCEMC_DictLN_Fun4AllBase.tagnum = -1 ;
  G__SubtractCEMC_DictLN_PHCompositeNode.tagnum = -1 ;
  G__SubtractCEMC_DictLN_SubsysReco.tagnum = -1 ;
  G__SubtractCEMC_DictLN_SubtractCEMC.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSubtractCEMC_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_string);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_SubsysReco);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SubtractCEMC_DictLN_SubtractCEMC),sizeof(SubtractCEMC),-1,66816,(char*)NULL,G__setup_memvarSubtractCEMC,G__setup_memfuncSubtractCEMC);
}
extern "C" void G__cpp_setupSubtractCEMC_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSubtractCEMC_Dict()");
  G__set_cpp_environmentSubtractCEMC_Dict();
  G__cpp_setup_tagtableSubtractCEMC_Dict();

  G__cpp_setup_inheritanceSubtractCEMC_Dict();

  G__cpp_setup_typetableSubtractCEMC_Dict();

  G__cpp_setup_memvarSubtractCEMC_Dict();

  G__cpp_setup_memfuncSubtractCEMC_Dict();
  G__cpp_setup_globalSubtractCEMC_Dict();
  G__cpp_setup_funcSubtractCEMC_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSubtractCEMC_Dict();
  return;
}
class G__cpp_setup_initSubtractCEMC_Dict {
  public:
    G__cpp_setup_initSubtractCEMC_Dict() { G__add_setup_func("SubtractCEMC_Dict",(G__incsetup)(&G__cpp_setupSubtractCEMC_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSubtractCEMC_Dict() { G__remove_setup_func("SubtractCEMC_Dict"); }
};
G__cpp_setup_initSubtractCEMC_Dict G__cpp_setup_initializerSubtractCEMC_Dict;

